#FROM golang:1.8.1
FROM golang:alpine
MAINTAINER "Francisco Moctezuma <yazpik@gmail.com>"

RUN apk add --update git bash openssh openssl make && \
    rm -rf /var/cache/apk/*

ENV TF_DEV=true

WORKDIR $GOPATH/src/github.com/terraform-providers
RUN git clone https://github.com/terraform-providers/terraform-provider-openstack ./ && \
    make build

WORKDIR $GOPATH

FROM golang:alpine

ENV TERRAFORM_VERSION=0.10.0-beta1

RUN apk add --update git bash openssh openssl && \
    rm -rf /var/cache/apk/*

ENV TF_DEV=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh

ENTRYPOINT ["terraform"]

