FROM golang:alpine
MAINTAINER "Francisco Moctezuma <yazpik@gmail.com>"

ENV TERRAFORM_VERSION=0.10.0-beta1

RUN apk add --update git bash openssh openssl && \
    rm -rf /var/cache/apk/*

ENV TF_DEV=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]
