# Building terraform and terraform openstack provider
FROM golang:alpine AS build-tf-os-provider
MAINTAINER "Francisco Moctezuma <yazpik@gmail.com>"

RUN apk add --update git make bash && \
    rm -rf /var/cache/apk/*

WORKDIR $GOPATH/src/github.com/terraform-providers
RUN git clone https://github.com/terraform-providers/terraform-provider-openstack && \
	cd terraform-provider-openstack && \
	make build

ENV TERRAFORM_VERSION=0.10.0-beta1
WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
        git checkout v${TERRAFORM_VERSION} && \
        make dev

## SECOND STAGE - Downloading prebuilds

FROM alpine:latest AS download-prebuilds
RUN apk add --update curl && \
       rm -rf /var/cache/apk/*

# Terraform binary
ENV SIGIL_VERSION=0.4.0
ENV KUBECTL_VERSION=stable

# Kubectl binary
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl 

# Sigil Binary
RUN curl -LO https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_${SIGIL_VERSION}_Linux_x86_64.tgz && \
    tar -zxf sigil_${SIGIL_VERSION}_Linux_x86_64.tgz 

# FINAL STAGE
FROM alpine:latest

ENV DOCKER_VERSION=17.03.1

RUN apk add --update --no-cache bash curl docker git jq make openrc openssh openssl && \
	rm -rf /var/cache/apk/*

RUN curl -Lo /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}-ce.tgz && \
    tar --extract --file /tmp/docker.tgz --strip-components 1 --directory /usr/local/bin/ && \
    curl -sL https://github.com/docker/docker/raw/master/hack/dind > /usr/local/bin/dind && \
    chmod +x /usr/local/bin/dind 


WORKDIR /k8s-installer

# Moving Binaries generated on early stages
COPY --from=build-tf-os-provider /go/bin/terraform-provider-openstack /k8s-installer
COPY --from=build-tf-os-provider /go/bin/terraform /usr/local/bin/
COPY --from=download-prebuilds ./sigil /usr/local/bin/
COPY --from=download-prebuilds ./kubectl /usr/local/bin/
