# Building terraform provider
FROM golang:alpine AS build-tf-os-provider
MAINTAINER "Francisco Moctezuma <yazpik@gmail.com>"

RUN apk add --update git openssh openssl make bash && \
    rm -rf /var/cache/apk/*

WORKDIR $GOPATH/src/github.com/terraform-providers
RUN git clone https://github.com/terraform-providers/terraform-provider-openstack && \
	cd terraform-provider-openstack && \
	make build

# Downloading prebuilds
FROM alpine:latest AS download-prebuilds

# Terraform binary
ENV TERRAFORM_VERSION=0.10.0-beta1
ENV TERRAFORM_SHA256SUM=9e14c850054faaaa3f40a1c28d8991fc4a42f0dc2d53564d8f60b12243c7ae5d
ENV SIGIL_VERSION=0.4.0
ENV KUBECTL_VERSION=stable
RUN apk add --update curl docker git make && \
    curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    echo "${TERRAFORM_SHA256SUM}  terraform_${TERRAFORM_VERSION}_linux_amd64.zip" > terraform_${TERRAFORM_VERSION}_SHA256SUMS && \
    sha256sum -cs terraform_${TERRAFORM_VERSION}_SHA256SUMS && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin && \
    rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Kubectl binary
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl

# Sigil Binary
RUN curl -LO https://github.com/gliderlabs/sigil/releases/download/v0.4.0/sigil_${SIGIL_VERSION}_Linux_x86_64.tgz \
    && tar -zxf sigil_${SIGIL_VERSION}_Linux_x86_64.tgz \
    && mv ./sigil /usr/local/bin/sigil

# Final stage and install pre-reqs
FROM alpine:latest
RUN apk add --update jq make openssh openssl && \
	rm -rf /var/cache/apk/*

WORKDIR /k8s-installer
COPY --from=build-tf-os-provider /go/bin/terraform-provider-openstack /k8s-installer
COPY --from=download-prebuilds /bin/terraform /usr/local/bin/
COPY --from=download-prebuilds /usr/local/bin/sigil /usr/local/bin/
COPY --from=download-prebuilds /usr/local/bin/kubectl /usr/local/bin/
ADD . .
